### ISSUE TITLE
running protractor leaves error

### ISSUE THREAD

**Issue by thoramrk** [thoramrk/webdriverio#1]
WARNING - pattern ./spec.js did not match any files.
[launcher] Process exited with error code 1
C:\Users\RK\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:126
                    throw e;
                    ^

Error: Spec patterns did not match any files.
    at Runner.run (C:\Users\RK\AppData\Roaming\npm\node_modules\protractor\lib\runner.js:269:11)
    at TaskRunner.run (C:\Users\RK\AppData\Roaming\npm\node_modules\protractor\lib\taskRunner.js:123:19)
    at createNextTaskRunner (C:\Users\RK\AppData\Roaming\npm\node_modules\protractor\lib\launcher.js:216:20)
    at C:\Users\RK\AppData\Roaming\npm\node_modules\protractor\lib\launcher.js:239:7
    at _fulfilled (C:\Users\RK\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:797:54)
    at self.promiseDispatch.done (C:\Users\RK\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:826:30)
    at Promise.promise.promiseDispatch (C:\Users\RK\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:759:13)
    at C:\Users\RK\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:573:44
    at flush (C:\Users\RK\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:108:17)
    at doNTCallback0 (node.js:430:9)

**Comment by thoramrk** [comment]
please help me guys
